knpu_oauth2_client:
    clients:
        discord:
            type: discord
            client_id: '%env(DISCORD_ID)%'
            client_secret: '%env(DISCORD_SECRET)%'
            redirect_route: connect_discord
            redirect_params: { }
        google:
            type: google
            client_id: '%env(GOOGLE_ID)%'
            client_secret: '%env(GOOGLE_SECRET)%'
            redirect_route: connect_google
            redirect_params: { }

        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
